# Generated by Django 5.2 on 2025-05-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimages',
            name='order',
        ),
    ]
