# Generated by Django 5.2 on 2025-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallbanner',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='smallbanner',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='smallbanner',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='smallbanner',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='smallbanner',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
