# Generated by Django 5.2 on 2025-05-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='order',
        ),
    ]
