# Generated by Django 5.2 on 2025-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_description_de_alter_blog_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
