# Generated by Django 5.2 on 2025-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_description_de_alter_blog_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructions',
            name='image',
            field=models.ImageField(default=1, upload_to='instructions/'),
            preserve_default=False,
        ),
    ]
