# Generated by Django 5.2 on 2025-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instructions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='image',
            field=models.ImageField(upload_to='instructions/'),
        ),
    ]
