# Generated by Django 5.2 on 2025-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triporder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
