# Generated by Django 5.2 on 2025-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_triporder_is_active_alter_triporder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triporder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
