# Generated by Django 5.2 on 2025-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instructions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='social',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='social',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='youtube',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='gmail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traditions',
            name='content_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traditions',
            name='content_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traditions',
            name='content_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traditions',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traditions',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='locations',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
