# Generated by Django 5.2 on 2025-05-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='order',
        ),
    ]
