# Generated by Django 5.2 on 2025-05-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='order',
        ),
    ]
