# Generated by Django 5.2 on 2025-05-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_triporder_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triporder',
            name='message',
        ),
    ]
