# Generated by Django 5.2 on 2025-05-16 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_contact_message_remove_social_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='small_banners')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.banner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
