# Generated by Django 5.2 on 2025-05-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimages',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trip'),
        ),
    ]
