# Generated by Django 5.2 on 2025-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20250528_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallbanner',
            name='order',
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='title_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
