# Generated by Django 5.2 on 2025-05-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tripimages_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
    ]
