# Generated by Django 5.1.7 on 2025-05-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_service_id_remove_service_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdays',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_day', to='main.trip'),
        ),
    ]
